hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

ribbon:
  MaxTotalConnections: 9000
  MaxConnectionsPerHost: 4500
  ReadTimeout: 10000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  semaphore:
    maxSemaphores: 1000
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    customer-service:
      path: /user/**
      serviceId: customer-service

    devicemanage-service:
      path: /device/**
      serviceId: devicemanage-service

    mqttservice-service:
      path: /mqtt/**
      serviceId: mqttservice-service

server:
  # port: ${PORT}
  port: 8080

spring:
  http:
    multipart:
      max-file-size: 52428800
      max-request-size: 104857600 #单次请求文件大小限制

#Matser的ip地址
redis:
  hostName: localhost
  #端口号
  port: 6379
  #如果有密码
  password: 123456
  #客户端超时时间单位是毫秒 默认是2000
  timeout: 10000
  #最大空闲数
  maxIdle: 300
  #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用maxTotal
  #maxActive: 600
  #控制一个pool可分配多少个jedis实例,用来替换上面的maxActive,如果是jedis 2.4以后用该属性
  maxTotal: 1000
  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  maxWaitMillis: 1000
  #连接的最小空闲时间 默认1800000毫秒(30分钟)
  minEvictableIdleTimeMillis: 300000
  #每次释放连接的最大数目,默认3
  numTestsPerEvictionRun: 1024
  #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  timeBetweenEvictionRunsMillis: 30000
  #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testOnBorrow: true
  #在空闲时检查有效性, 默认false
  testWhileIdle: true